package com.vela.android.lab.db.room.migrations

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/** Additive only: no v7 row/column rewrite, no backfill, no deletion. */
val MIGRATION_7_8: Migration = object : Migration(7, 8) {
    override fun migrate(db: SupportSQLiteDatabase) {
        POSITION_EVIDENCE_V8_SQL.forEach { db.execSQL(it) }
    }
}

internal val POSITION_EVIDENCE_V8_SQL: List<String> = listOf(
    "CREATE TABLE IF NOT EXISTS `paper_broker_snapshot` (`snapshotId` TEXT NOT NULL, `sequence` INTEGER NOT NULL, `manualRefreshId` TEXT NOT NULL, `accountRef` TEXT, `source` TEXT NOT NULL, `parserVersion` TEXT NOT NULL, `configRef` TEXT NOT NULL, `sessionRef` TEXT NOT NULL, `startedAtEpochMillis` INTEGER NOT NULL, `accountCompletedAtEpochMillis` INTEGER, `positionsCompletedAtEpochMillis` INTEGER, `completedAtEpochMillis` INTEGER NOT NULL, `startedMonotonicNanos` INTEGER NOT NULL, `completedMonotonicNanos` INTEGER NOT NULL, `accountRequestOutcome` TEXT NOT NULL, `positionsRequestOutcome` TEXT NOT NULL, `accountHttpStatus` INTEGER, `positionsHttpStatus` INTEGER, `positionsReceivedCount` INTEGER NOT NULL, `positionsValidatedCount` INTEGER NOT NULL, `completeness` TEXT NOT NULL, `diagnosticsJson` TEXT NOT NULL, `persistedAtEpochMillis` INTEGER NOT NULL, `observedAccountJson` TEXT, `localHistoryDigest` TEXT NOT NULL, `localHistoryStable` INTEGER NOT NULL, `orderSequenceInclusive` INTEGER NOT NULL, `lifecycleSequenceInclusive` INTEGER NOT NULL, PRIMARY KEY(`snapshotId`))",
    "CREATE UNIQUE INDEX IF NOT EXISTS `index_paper_broker_snapshot_manualRefreshId` ON `paper_broker_snapshot` (`manualRefreshId`)",
    "CREATE UNIQUE INDEX IF NOT EXISTS `index_paper_broker_snapshot_sequence` ON `paper_broker_snapshot` (`sequence`)",
    "CREATE TABLE IF NOT EXISTS `paper_broker_position_snapshot` (`snapshotId` TEXT NOT NULL, `symbol` TEXT NOT NULL, `rowIndex` INTEGER NOT NULL, `side` TEXT NOT NULL, `qtyRawDecimal` TEXT NOT NULL, `qtyCanonicalDecimal` TEXT NOT NULL, `decimalProvenance` TEXT NOT NULL, PRIMARY KEY(`snapshotId`, `symbol`), FOREIGN KEY(`snapshotId`) REFERENCES `paper_broker_snapshot`(`snapshotId`) ON UPDATE NO ACTION ON DELETE NO ACTION)",
    "CREATE UNIQUE INDEX IF NOT EXISTS `index_paper_broker_position_snapshot_snapshotId_rowIndex` ON `paper_broker_position_snapshot` (`snapshotId`, `rowIndex`)",
    "CREATE TABLE IF NOT EXISTS `paper_position_anchor` (`anchorId` TEXT NOT NULL, `symbol` TEXT NOT NULL, `accountRef` TEXT NOT NULL, `brokerSnapshotId` TEXT NOT NULL, `baselineQty` TEXT NOT NULL, `baselineProvenance` TEXT NOT NULL, `orderSequenceInclusive` INTEGER NOT NULL, `lifecycleSequenceInclusive` INTEGER NOT NULL, `cutAssurance` TEXT NOT NULL, `status` TEXT NOT NULL, `activeKey` TEXT, `createdAtEpochMillis` INTEGER NOT NULL, `invalidatedAtEpochMillis` INTEGER, `invalidationReason` TEXT, `version` INTEGER NOT NULL, PRIMARY KEY(`anchorId`), FOREIGN KEY(`brokerSnapshotId`) REFERENCES `paper_broker_snapshot`(`snapshotId`) ON UPDATE NO ACTION ON DELETE NO ACTION)",
    "CREATE INDEX IF NOT EXISTS `index_paper_position_anchor_brokerSnapshotId` ON `paper_position_anchor` (`brokerSnapshotId`)",
    "CREATE UNIQUE INDEX IF NOT EXISTS `index_paper_position_anchor_activeKey` ON `paper_position_anchor` (`activeKey`)",
    "CREATE INDEX IF NOT EXISTS `index_paper_position_anchor_accountRef_symbol` ON `paper_position_anchor` (`accountRef`, `symbol`)",
    "CREATE TABLE IF NOT EXISTS `paper_position_anchor_cursor` (`anchorId` TEXT NOT NULL, `attemptId` TEXT NOT NULL, `orderId` TEXT, `clientOrderId` TEXT, `orderSequenceId` INTEGER, `symbol` TEXT, `side` TEXT, `includedFilledQty` TEXT NOT NULL, `provenance` TEXT NOT NULL, `observationSequence` INTEGER NOT NULL, `payloadFingerprint` TEXT NOT NULL, PRIMARY KEY(`anchorId`, `attemptId`), FOREIGN KEY(`anchorId`) REFERENCES `paper_position_anchor`(`anchorId`) ON UPDATE NO ACTION ON DELETE NO ACTION)",
    "CREATE TABLE IF NOT EXISTS `paper_position_anchor_event` (`eventId` TEXT NOT NULL, `anchorId` TEXT NOT NULL, `version` INTEGER NOT NULL, `type` TEXT NOT NULL, `timestampEpochMillis` INTEGER NOT NULL, `reason` TEXT, `evidenceSnapshotId` TEXT NOT NULL, PRIMARY KEY(`eventId`), FOREIGN KEY(`anchorId`) REFERENCES `paper_position_anchor`(`anchorId`) ON UPDATE NO ACTION ON DELETE NO ACTION)",
    "CREATE UNIQUE INDEX IF NOT EXISTS `index_paper_position_anchor_event_anchorId_version` ON `paper_position_anchor_event` (`anchorId`, `version`)",
    "CREATE TABLE IF NOT EXISTS `paper_position_reconciliation_report` (`reportId` TEXT NOT NULL, `brokerSnapshotId` TEXT NOT NULL, `engineVersion` TEXT NOT NULL, `policyVersion` TEXT NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `accountRef` TEXT, `matchedCount` INTEGER NOT NULL, `mismatchedCount` INTEGER NOT NULL, `unanchoredCount` INTEGER NOT NULL, `unknownCount` INTEGER NOT NULL, `diagnosticsJson` TEXT NOT NULL, `inputsJson` TEXT NOT NULL, `inputsDigest` TEXT NOT NULL, `freshness` TEXT NOT NULL, `localEvidenceAlignment` TEXT NOT NULL, PRIMARY KEY(`reportId`), FOREIGN KEY(`brokerSnapshotId`) REFERENCES `paper_broker_snapshot`(`snapshotId`) ON UPDATE NO ACTION ON DELETE NO ACTION)",
    "CREATE INDEX IF NOT EXISTS `index_paper_position_reconciliation_report_brokerSnapshotId` ON `paper_position_reconciliation_report` (`brokerSnapshotId`)",
    "CREATE TABLE IF NOT EXISTS `paper_position_reconciliation_row` (`reportId` TEXT NOT NULL, `symbol` TEXT NOT NULL, `brokerQty` TEXT, `brokerProvenance` TEXT NOT NULL, `knownVelaDelta` TEXT, `knownDeltaProvenance` TEXT NOT NULL, `knownDeltaComplete` INTEGER NOT NULL, `anchorQty` TEXT, `anchorProvenance` TEXT NOT NULL, `expectedQty` TEXT, `expectedProvenance` TEXT NOT NULL, `difference` TEXT, `state` TEXT NOT NULL, `presence` TEXT NOT NULL, `diagnosticsJson` TEXT NOT NULL, `anchorId` TEXT, `cause` TEXT, PRIMARY KEY(`reportId`, `symbol`), FOREIGN KEY(`reportId`) REFERENCES `paper_position_reconciliation_report`(`reportId`) ON UPDATE NO ACTION ON DELETE NO ACTION, FOREIGN KEY(`anchorId`) REFERENCES `paper_position_anchor`(`anchorId`) ON UPDATE NO ACTION ON DELETE NO ACTION)",
    "CREATE INDEX IF NOT EXISTS `index_paper_position_reconciliation_row_anchorId` ON `paper_position_reconciliation_row` (`anchorId`)",
    "CREATE TABLE IF NOT EXISTS `paper_order_decimal_evidence` (`observationId` INTEGER NOT NULL, `field` TEXT NOT NULL, `attemptId` TEXT NOT NULL, `orderId` TEXT NOT NULL, `clientOrderId` TEXT NOT NULL, `symbol` TEXT NOT NULL, `side` TEXT NOT NULL, `orderSequenceId` INTEGER NOT NULL, `accountRef` TEXT NOT NULL, `rawDecimal` TEXT NOT NULL, `canonicalDecimal` TEXT NOT NULL, `provenance` TEXT NOT NULL, `payloadFingerprint` TEXT NOT NULL, `parserVersion` TEXT NOT NULL, `recordedAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`observationId`, `field`), FOREIGN KEY(`observationId`) REFERENCES `paper_order_lifecycle_observation`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION)",
    "CREATE INDEX IF NOT EXISTS `index_paper_order_decimal_evidence_attemptId` ON `paper_order_decimal_evidence` (`attemptId`)",
)
