package com.vela.android.lab.db.room.entities

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Phase 2.o local-only audit row for a Paper order **dry-run**
 * preflight evaluation.
 *
 * **No real order was sent.** This row records the evaluation of a
 * *hypothetical* Paper trade so the operator can review what would
 * have happened. The Phase 2.m safety contract still holds:
 * `AlpacaHttpClient` exposes only `executeGet`, and
 * `PaperTradingExecutionGuard.canExecuteOrders` is hard-coded `false`.
 *
 * **No credential value, no API key, and no Alpaca account id is
 * stored.** The entity stores only:
 *
 *  - intent fields (symbol, side, type, tif, quantity, optional
 *    limit price);
 *  - preflight engine output (status, estimated notional, hypothetical
 *    buying power after, hypothetical allocation after, latest local
 *    price used, price source/freshness/age, latest signal state at
 *    preflight time, market-open flag);
 *  - short human-readable summary strings of block reasons and
 *    warnings (one line per condition);
 *  - the `clientDryRunId` UUID generated by the preflight VM;
 *  - timestamps in epoch millis.
 *
 * The Phase 2.n reflection contract test scans every declared field
 * to ensure no `apiKey`, `secret`, `accountId`, or `apca` field
 * exists on this entity.
 */
@Entity(
    tableName = "paper_order_dry_run_audits",
    indices = [
        Index(
            value = ["createdAtEpochMillis"],
            name = "ix_paper_dry_run_created_at",
        ),
        Index(
            value = ["symbol", "createdAtEpochMillis"],
            name = "ix_paper_dry_run_symbol_created_at",
        ),
        Index(
            value = ["clientDryRunId"],
            name = "ix_paper_dry_run_client_id",
            unique = true,
        ),
    ],
)
data class PaperOrderDryRunAuditEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0L,
    val clientDryRunId: String,
    val createdAtEpochMillis: Long,
    val symbol: String,
    val side: String,
    val orderType: String,
    val timeInForce: String,
    val quantity: Double,
    val limitPriceUsd: Double?,
    val status: String,
    val estimatedNotionalUsd: Double?,
    val buyingPowerAfterUsd: Double?,
    val allocationPercentAfter: Double?,
    val latestPriceUsedUsd: Double?,
    val priceSource: String?,
    val priceFreshness: String?,
    val priceAgeMillis: Long?,
    val latestSignalState: String?,
    val marketOpen: Boolean?,
    /** Newline-separated short messages (one per block reason). */
    val blockReasonsSummary: String,
    /** Newline-separated short messages (one per warning). */
    val warningsSummary: String,
    /** Always `MANUAL_DRY_RUN` for Phase 2.n. */
    val source: String,
)
